### ISSUE TITLE
Add kmFit isSingular warning

### ISSUE THREAD

**Issue by kdillmcfarland** [BIGslu/kimma#3]
**Is your feature request related to a problem? Please describe.**
Currently, kmFit prints a "boundary (singular) fit: see ?isSingular" warning to the console for each gene that cannot be fit. 

**Describe the solution you'd like**
It would be helpful to collapse these into a single warning like  
`X of Y genes could not be fit due to boundary (singular) fit. See ?isSingular`

**Describe alternatives you've considered**
NA

**Comment by basilinb** [comment]
Suggest we save the list of failed genes to the result object
